times = ('Botafogo', 'Palmeiras', 'Flamengo', 'Fluminense', 'Grêmio', 
'Athletico-PR', 'Bragantino', 'Fortaleza', 'Cuiabá', 'São Paulo')
print('-=' * 40)
print(f'Lista de times do Brasileirão {times}')
print('-=' * 40)
print(f'Os 5 primeiros são {times[0:5]}')
print('-=' * 40)
print(f'Os 4 últimos são {times[6:]}')
print('-=' * 40)
print(f'Times em ordem alfabética: {sorted(times)}')
print('-=' * 40)
print(f'O Forteleza está na {times.index("Fortaleza")+1}ª posição')
